# Generated by Django 4.2.16 on 2024-12-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0015_category_toy_toy_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('picture_fn', models.CharField(max_length=256)),
            ],
        ),
    ]
