# Generated by Django 4.2.16 on 2024-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0016_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='discont',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='presents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
