# Generated by Django 4.2.16 on 2024-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0017_action_discont_action_presents_action_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='actual',
            field=models.BooleanField(default=False),
        ),
    ]
