# Generated by Django 4.2.16 on 2024-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0018_action_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
