# Generated by Django 4.2.16 on 2024-12-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0022_remove_buyer_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='age_limited',
        ),
    ]
